### ISSUE TITLE
Sending messages too quickly

### ISSUE THREAD

**Issue by Den4200** [Den4200/pyfrost#13]
When sending messages too quickly in rapid succession, an unpickling error is thrown on the server, just like the one in #8.

```py
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Users\dpham\AppData\Local\Programs\Python\Python37\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "C:\Users\dpham\AppData\Local\Programs\Python\Python37\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "D:\dpham\Desktop\code\pyfrost\frost\server\server.py", line 67, in on_user_connect
    data = self.recieve(conn)
  File "D:\dpham\Desktop\code\pyfrost\frost\server\socketio\base_server.py", line 85, in recieve
    return pickle.loads(result)
_pickle.UnpicklingError: invalid load key, '\x00'.
```
This is because packets from different messages are being sent at the same time to the server, so it jumbles them all together, causing this error shown above. The client keeps running, but its connection is severed from the server, so the client must restart in order to reconnect.

## Proposed Solution
Add a cooldown between messages sent over on the client side.

**Comment by Den4200** [comment]
It seems like this error does no happen anymore after the last few commits. It seems to have disappeared. Now, when sending messages to quickly, some messages are just dropped and never recorded.

**Comment by Den4200** [comment]
After migrating to using a database, messages sent in rapid succession are all recorded and stored in the database. However, all clients do not receive every single message. A few messages are dropped and never received by the clients. The dropped messages are random and different between different clients.
