### ISSUE TITLE
Cross-platform compatibility between the server and client

### ISSUE THREAD

**Issue by Den4200** [Den4200/pyfrost#8]
When hosting a server on Windows, Linux users cannot send any data after connecting without error. The same presumably also happens when a Linux user hosts a server and a Windows user connects and tries to send data. Pickle causes this issue, raising an unpickling error on the server side.

```py
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Users\dpham\AppData\Local\Programs\Python\Python37\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "C:\Users\dpham\AppData\Local\Programs\Python\Python37\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "D:\dpham\Desktop\code\pyfrost\frost\server\server.py", line 67, in on_user_connect
    data = self.recieve(conn)
  File "D:\dpham\Desktop\code\pyfrost\frost\server\socketio\base_server.py", line 85, in recieve
    return pickle.loads(result)
_pickle.UnpicklingError: invalid load key, '\x00'.
```

The server continues on just fine, but the client stays frozen expecting a response from the server. This response never comes, so the client just keeps waiting.

## Proposed Solutions
- ~~Use protocol 0 with pickle~~ (Did not solve the issue)
- Encode the payload with base64 before sending it off and decode at the receiving point

**Comment by Den4200** [comment]
This issue is no longer relevant, since pickle is no longer being used in this library.
